# -*- makefile -*-
#

bin_PROGRAMS		= allgather_f90 \
                          allgatherv_f90 \
                          allreduce_f90 \
                          alltoall_f90 \
                          alltoallv_f90 \
                          alltoallw_f90 \
                          exscan_f90 \
                          gather_f90 \
                          gatherv_f90 \
                          reduce_f90 \
                          reduce_loc_f90 \
                          reduce_scatter_f90 \
                          reduce_scatter_block_f90 \
                          scan_f90 \
                          scatter_f90 \
                          scatterv_f90 \
                          allgather_f08 \
                          allgatherv_f08 \
                          allreduce_f08 \
                          alltoall_f08 \
                          alltoallv_f08 \
                          alltoallw_f08 \
                          bcast_f08 \
                          exscan_f08 \
                          gather_f08 \
                          gatherv_f08 \
                          reduce_f08 \
                          reduce_loc_f08 \
                          reduce_scatter_f08 \
                          reduce_scatter_block_f08 \
                          scan_f08 \
                          scatter_f08 \
                          scatter_init_f08 \
                          scatterv_f08 \
                          ineighbor_alltoallv_f90 \
                          ineighbor_alltoallw_f90 \
                          neighbor_alltoallv_f90  \
                          neighbor_alltoallv_init_f90 \
                          neighbor_alltoallw_f90 \
                          neighbor_alltoallw_init_f90 \
                          ineighbor_alltoallv_f08 \
                          ineighbor_alltoallw_f08 \
                          neighbor_alltoallv_f08 \
                          neighbor_alltoallv_init_f08 \
                          neighbor_alltoallw_f08 \
                          neighbor_alltoallw_init_f08 \
                          ibarrier_f90 \
                          ibcast_f90 \
                          iallgather_f90 \
                          ireduce_scatter_f90 \
                          ireduce_scatter_block_f90 \
                          iallgatherv_f90 \
                          iallreduce_f90 \
                          iscan_f90 \
                          iscatter_f90 \
                          iscatterv_f90 \
                          ibarrier_f08 \
                          ibcast_f08 \
                          iallgather_f08 \
                          ireduce_scatter_f08 \
                          ireduce_scatter_block_f08 \
                          iallgatherv_f08 \
                          iallreduce_f08 \
                          iscan_f08 \
                          iscatter_f08 \
                          iscatterv_f08 \
                          allgather_init_f90 \
                          allgatherv_init_f90 \
                          allreduce_init_f90 \
                          alltoall_init_f90 \
                          alltoallv_init_f90 \
                          alltoallw_init_f90 \
                          barrier_init_f90 \
                          bcast_init_f90 \
                          gather_init_f90 \
                          gatherv_init_f90 \
                          reduce_init_f90 \
                          reduce_scatter_block_init_f90 \
                          reduce_scatter_init_f90 \
                          scan_init_f90 \
                          scatter_init_f90 \
                          scatterv_init_f90 \
                          allgather_init_f08 \
                          allgatherv_init_f08 \
                          allreduce_init_f08 \
                          alltoall_init_f08 \
                          alltoallv_init_f08 \
                          alltoallw_init_f08 \
                          barrier_init_f08 \
                          bcast_init_f08 \
                          gather_init_f08 \
                          gatherv_init_f08 \
                          reduce_init_f08 \
                          reduce_scatter_block_init_f08 \
                          reduce_scatter_init_f08 \
                          scan_init_f08 \
                          scatterv_init_f08

bcast_f08_SOURCES       = bcast_f08.f90
ibarrier_f90_SOURCES    = ibarrier_f90.f90
ibarrier_f08_SOURCES    = ibarrier_f08.f90
ibcast_f90_SOURCES    = ibcast_f90.f90
ibcast_f08_SOURCES    = ibcast_f08.f90
barrier_init_f90_SOURCES  = barrier_init_f90.f90
barrier_init_f08_SOURCES  = barrier_init_f08.f90
bcast_init_f90_SOURCES  = bcast_init_f90.f90
bcast_init_f08_SOURCES  = bcast_init_f08.f90
ineighbor_alltoallv_f90_SOURCES = ineighbor_alltoallv_f90.f90
ineighbor_alltoallw_f90_SOURCES = ineighbor_alltoallw_f90.f90
neighbor_alltoallv_f90_SOURCES = neighbor_alltoallv_f90.f90
neighbor_alltoallv_init_f90_SOURCES = neighbor_alltoallv_init_f90.f90
neighbor_alltoallw_f90_SOURCES = neighbor_alltoallw_f90.f90
neighbor_alltoallw_init_f90_SOURCES = neighbor_alltoallw_init_f90.f90
ineighbor_alltoallv_f08_SOURCES = ineighbor_alltoallv_f08.f90
ineighbor_alltoallw_f08_SOURCES = ineighbor_alltoallw_f08.f90
neighbor_alltoallv_f08_SOURCES = neighbor_alltoallv_f08.f90
neighbor_alltoallv_init_f08_SOURCES = neighbor_alltoallv_init_f08.f90
neighbor_alltoallw_f08_SOURCES = neighbor_alltoallw_f08.f90
neighbor_alltoallw_init_f08_SOURCES = neighbor_alltoallw_init_f08.f90
allgather_f90_SOURCES = allgather_f90.f90
allgather_init_f90_SOURCES = allgather_init_f90.f90
allgatherv_f90_SOURCES = allgatherv_f90.f90
allgatherv_init_f90_SOURCES = allgatherv_init_f90.f90
allreduce_f90_SOURCES = allreduce_f90.f90
allreduce_init_f90_SOURCES = allreduce_init_f90.f90
alltoall_f90_SOURCES = alltoall_f90.f90
alltoall_init_f90_SOURCES = alltoall_init_f90.f90
alltoallv_f90_SOURCES = alltoallv_f90.f90
alltoallv_init_f90_SOURCES = alltoallv_init_f90.f90
alltoallw_f90_SOURCES = alltoallw_f90.f90
alltoallw_init_f90_SOURCES = alltoallw_init_f90.f90
exscan_f90_SOURCES = exscan_f90.f90
gather_f90_SOURCES = gather_f90.f90
gather_init_f90_SOURCES = gather_init_f90.f90
gatherv_f90_SOURCES = gatherv_f90.f90
gatherv_init_f90_SOURCES = gatherv_init_f90.f90
iallgather_f90_SOURCES = iallgather_f90.f90
iallgatherv_f90_SOURCES = iallgatherv_f90.f90
iallreduce_f90_SOURCES = iallreduce_f90.f90
ireduce_scatter_f90_SOURCES = ireduce_scatter_f90.f90
ireduce_scatter_block_f90_SOURCES = ireduce_scatter_block_f90.f90
iscan_f90_SOURCES = iscan_f90.f90
iscatter_f90_SOURCES = iscatter_f90.f90
iscatterv_f90_SOURCES = iscatterv_f90.f90
reduce_f90_SOURCES = reduce_f90.f90
reduce_init_f90_SOURCES = reduce_init_f90.f90
reduce_loc_f90_SOURCES = reduce_loc_f90.f90
reduce_scatter_f90_SOURCES = reduce_scatter_f90.f90
reduce_scatter_block_f90_SOURCES = reduce_scatter_block_f90.f90
reduce_scatter_block_init_f90_SOURCES = reduce_scatter_block_init_f90.f90
reduce_scatter_init_f90_SOURCES = reduce_scatter_init_f90.f90
scan_f90_SOURCES = scan_f90.f90
scan_init_f90_SOURCES = scan_init_f90.f90
scatter_f90_SOURCES = scatter_f90.f90
scatter_init_f90_SOURCES = scatter_init_f90.f90
scatterv_f90_SOURCES = scatterv_f90.f90
scatterv_init_f90_SOURCES = scatterv_init_f90.f90
allgather_f08_SOURCES = allgather_f08.f90
allgather_init_f08_SOURCES = allgather_init_f08.f90
allgatherv_f08_SOURCES = allgatherv_f08.f90
allgatherv_init_f08_SOURCES = allgatherv_init_f08.f90
allreduce_f08_SOURCES = allreduce_f08.f90
allreduce_init_f08_SOURCES = allreduce_init_f08.f90
alltoall_f08_SOURCES = alltoall_f08.f90
alltoall_init_f08_SOURCES = alltoall_init_f08.f90
alltoallv_f08_SOURCES = alltoallv_f08.f90
alltoallv_init_f08_SOURCES = alltoallv_init_f08.f90
alltoallw_f08_SOURCES = alltoallw_f08.f90
alltoallw_init_f08_SOURCES = alltoallw_init_f08.f90
exscan_f08_SOURCES = exscan_f08.f90
gather_f08_SOURCES = gather_f08.f90
gather_init_f08_SOURCES = gather_init_f08.f90
gatherv_f08_SOURCES = gatherv_f08.f90
gatherv_init_f08_SOURCES = gatherv_init_f08.f90
iallgather_f08_SOURCES = iallgather_f08.f90
iallgatherv_f08_SOURCES = iallgatherv_f08.f90
iallreduce_f08_SOURCES = iallreduce_f08.f90
ireduce_scatter_f08_SOURCES = ireduce_scatter_f08.f90
ireduce_scatter_block_f08_SOURCES = ireduce_scatter_block_f08.f90
iscan_f08_SOURCES = iscan_f08.f90
iscatter_f08_SOURCES = iscatter_f08.f90
iscatterv_f08_SOURCES = iscatterv_f08.f90
reduce_f08_SOURCES = reduce_f08.f90
reduce_init_f08_SOURCES = reduce_init_f08.f90
reduce_loc_f08_SOURCES = reduce_loc_f08.f90
reduce_scatter_f08_SOURCES = reduce_scatter_f08.f90
reduce_scatter_block_f08_SOURCES = reduce_scatter_block_f08.f90
reduce_scatter_block_init_f08_SOURCES = reduce_scatter_block_init_f08.f90
reduce_scatter_init_f08_SOURCES = reduce_scatter_init_f08.f90
scan_f08_SOURCES = scan_f08.f90
scan_init_f08_SOURCES = scan_init_f08.f90
scatter_f08_SOURCES = scatter_f08.f90
scatter_init_f08_SOURCES = scatter_init_f08.f90
scatterv_f08_SOURCES = scatterv_f08.f90
scatterv_init_f08_SOURCES = scatterv_init_f08.f90
